name: stlfemsolver-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.0
  - aiosignal=1.4.0
  - aom=3.9.1
  - attrs=25.4.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cctools_osx-arm64=1024.3
  - certifi=2025.10.5
  - cftime=1.6.4
  - clang=19.1.7
  - clang-19=19.1.7
  - clang_impl_osx-arm64=19.1.7
  - clang_osx-arm64=19.1.7
  - clangxx=19.1.7
  - clangxx_impl_osx-arm64=19.1.7
  - clangxx_osx-arm64=19.1.7
  - cli11=2.5.0
  - compiler-rt=19.1.7
  - compiler-rt_osx-arm64=19.1.7
  - contourpy=1.3.3
  - cpython=3.12.12
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.3.1
  - eigen=3.4.0
  - expat=2.7.1
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - ffmpeg=8.0.0
  - fftw=3.3.10
  - fmt=11.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - frozenlist=1.7.0
  - gdk-pixbuf=2.44.3
  - glslang=16.0.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h5py=3.15.1
  - harfbuzz=12.1.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hypre=2.32.0
  - icu=75.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - jsoncpp=1.9.6
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld64_osx-arm64=955.13
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libamd=3.3.3
  - libass=0.17.4
  - libblas=3.9.0
  - libboost=1.88.0
  - libboost-devel=1.88.0
  - libboost-headers=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp19.1=19.1.7
  - libclang13=21.1.3
  - libcolamd=3.3.4
  - libcurl=8.14.1
  - libcxsparse=4.4.1
  - libcxx=21.1.3
  - libcxx-devel=19.1.7
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - libllvm19=19.1.7
  - libllvm21=21.1.3
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.2.0
  - libopenvino-arm-cpu-plugin=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libparu=1.0.0
  - libpng=1.6.50
  - libpq=18.0
  - libprotobuf=6.31.1
  - libptscotch=7.0.10
  - librbio=4.3.4
  - librsvg=2.60.0
  - libscotch=7.0.10
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libsuitesparseconfig=7.10.1
  - libtheora=1.1.1
  - libtiff=4.7.1
  - libumfpack=6.3.5
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxslt=1.1.43
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.3
  - llvm-tools=19.1.7
  - llvm-tools-19=19.1.7
  - loguru=0.7.3
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - matplotlib-base=3.10.7
  - mdurl=0.1.2
  - meshio=5.3.5
  - metis=5.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0.1
  - mpi4py=4.1.1
  - mpich=4.3.2
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - mumps-include=5.8.1
  - mumps-mpi=5.8.1
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf4=1.7.3
  - nlohmann_json=3.12.0
  - numpy=2.3.3
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - pango=1.56.4
  - parmetis=4.0.3
  - pcre2=10.46
  - petsc=3.24.0
  - petsc4py=3.24.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - proj=9.7.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pugixml=1.15
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - qhull=2020.2
  - qt6-main=6.9.3
  - readline=8.3
  - rich=14.2.0
  - scalapack=2.2.0
  - sdl2=2.32.56
  - sdl3=3.2.24
  - setuptools=80.9.0
  - shaderc=2025.4
  - sigtool=0.1.3
  - six=1.17.0
  - slepc=3.24.0
  - slepc4py=3.24.0
  - snappy=1.2.2
  - spirv-tools=2025.4
  - sqlite=3.50.2
  - suitesparse=7.10.1
  - superlu=7.0.0
  - superlu_dist=9.1.0
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tapi=1300.6.5
  - tbb=2022.2.0
  - tbb-devel=2022.2.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - utfcpp=4.0.8
  - vtk=9.5.2
  - vtk-base=9.5.2
  - vtk-io-ffmpeg=9.5.2
  - wheel=0.45.1
  - wslink=2.4.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - gmsh==4.14.1
      - iniconfig==2.3.0
      - numpy-stl==3.2.0
      - pluggy==1.6.0
      - pytest==8.4.2
      - python-utils==3.9.1
prefix: /opt/anaconda3/envs/stlfemsolver-env
